apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asyncgate

resources:
- namespace.yaml
- configmap.yaml
- postgres.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

# Secret must be created manually or via sealed-secrets
# Don't include secret.yaml here
