apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asyncgate-dev

bases:
- ../../base

nameSuffix: -dev

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: asyncgate
- patch: |-
    - op: replace
      path: /data/ASYNCGATE_ENV
      value: "development"
  target:
    kind: ConfigMap
    name: asyncgate-config
